package e2e_config

// FIXME
// JIRA:- https://mayadata.atlassian.net/browse/MQ-3807

// diskPoolAPIVersionMap maps apiVersion of diskpool CRD with mayastor release version
// develop key will always hold the current diskpool apiVersion
// we need to update this map with each release which includes adding one key for that
// release and update the value for develop key, if needed.
var diskPoolAPIVersionMap = map[string]string{
	"develop": "openebs.io/v1beta2",
	"2.0.0":   "openebs.io/v1alpha1",
	"2.0.1":   "openebs.io/v1alpha1",
	"2.1.0":   "openebs.io/v1alpha1",
	"2.2.0":   "openebs.io/v1alpha1",
	"2.3.0":   "openebs.io/v1alpha1",
	"2.4.0":   "openebs.io/v1beta1",
	"2.5.0":   "openebs.io/v1beta1",
	"2.6.0":   "openebs.io/v1beta2",
}

var mayastorConfig = ProductSpec{
	AgentCoreContainerName:           "agent-core",
	AlertManagerPodPrefix:            "alertmanager",
	ControlPlaneAgent:                "mayastor-agent-core",
	ControlPlaneCoreAgent:            "mayastor-agent-core",
	ControlPlaneCsiController:        "mayastor-csi-controller",
	ControlPlaneEtcd:                 "mayastor-etcd",
	ControlPlanePoolOperator:         "mayastor-operator-diskpool",
	ControlPlaneRestServer:           "mayastor-api-rest",
	ControlPlaneLocalpvProvisioner:   "mayastor-localpv-provisioner",
	ControlPlaneObsCallhome:          "mayastor-obs-callhome",
	CpuCount:                         "2",
	CrdGroupName:                     "openebs.io",
	CrdPoolsResourceName:             "diskpools",
	CsiDaemonsetName:                 "mayastor-csi-node",
	CsiNodeServiceAppLabel:           "csi-node",
	CsiNodeServiceDaemonset:          "mayastor-csi-node",
	CsiNodeContainerName:             "csi-node",
	CsiProvisioner:                   "io.openebs.csi-mayastor",
	DaemonsetName:                    "mayastor-io-engine",
	DataPlaneNats:                    "nats",
	DockerOrganisation:               "openebs",
	EngineLabel:                      "openebs.io/engine",
	EngineLabelValue:                 "mayastor",
	EtcdYaml:                         "etcd",
	EventBusNatsSts:                  "mayastor-nats",
	HaNodeAgentDs:                    "mayastor-agent-ha-node",
	HaNodeAgentPodPrefix:             "mayastor-agent-ha-node",
	HelmReleaseName:                  "mayastor",
	IOEnginePodLabelValue:            "io-engine",
	IOEnginePodName:                  "mayastor-io-engine",
	JaegersCrdName:                   "jaegers.jaegertracing.io",
	KubectlPluginName:                "kubectl-mayastor",
	KubectlPluginPort:                30011,
	LogConfigResources:               []string{"mayastor-etcd", "mayastor-loki", "mayastor-promtail", "mayastor-io-engine", "mayastor-agent-core", "mayastor-agent-ha-node", "mayastor-csi-controller", "mayastor-csi-node", "mayastor-agent-license", "mayastor-operator-diskpool", "mayastor-api-rest", "mayastor-localpv-provisioner", "mayastor-obs-callhome"},
	LogDumpCsiAttacherName:           "csi-attacher",
	LogDumpCsiDriverRegistrarName:    "csi-driver-registrar",
	LogDumpCsiProvisionerName:        "csi-provisioner",
	LogDumpCsiResizerName:            "csi-resizer",
	LogDumpCsiSnapshotControllerName: "csi-snapshot-controller",
	LogDumpCsiSnapshotterName:        "csi-snapshotter",
	LogDumpDirs:                      []string{"agent-core", "csi-controller", "operator-diskpool", "api-rest"},
	LogDumpEngineLabel:               "io-engine",
	LogDumpHaClusterName:             "agent-ha-cluster",
	LogDumpMetricsExporterLabel:      "metrics-exporter",
	LoggingLabel:                     "openebs.io/logging",
	LogLevel:                         "debug",
	LokiStatefulset:                  "mayastor-loki",
	MetricsPollingInterval:           "30s",
	MongoAuthDatabase:                "test",
	MongoAuthPassword:                "admin123",
	MongoAuthRootPassword:            "r00tAdmin",
	MongoAuthUsername:                "admin",
	MongoDatabasePort:                27017,
	MongoDefaultChartVersion:         "14.5.0",
	MongoHelmRepo:                    "bitnami/mongodb",
	MongoHelmRepoName:                "bitnami",
	MongoHelmRepoUrl:                 "https://charts.bitnami.com/bitnami",
	MongoReleaseName:                 "ms-mongo",
	NatsPort:                         "4222",
	NvmeControllerModel:              "Mayastor NVMe controller",
	PartialRebuildCpTimeout:          "240s",
	PodLabelKey:                      "app",
	PoolCrdName:                      "diskpools.openebs.io",
	ProductName:                      "mayastor",
	ProductNamespace:                 "mayastor",
	PrometheusPodPrefix:              "prometheus",
	PrometheusPort:                   30090,
	PromtailDaemonsetName:            "mayastor-promtail",
	RestApiPort:                      8081,
	RestApiService:                   "mayastor-api-rest",
	StatsConfigMapName:               "mayastor-event-store",
	StatsDeployment:                  "mayastor-obs-callhome",
	StatsPort:                        "9090",
	StatsService:                     "mayastor-obs-callhome-stats",
	UpgradePodLabelValue:             "upgrade",
	DiskPoolAPIVersionMap:            diskPoolAPIVersionMap,
	ChartName:                        "mayastor/mayastor",
	ChartVersion:                     "0.0.0-main",
}
