// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: bdev.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBdevOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListBdevOptions) Reset() {
	*x = ListBdevOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bdev_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBdevOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBdevOptions) ProtoMessage() {}

func (x *ListBdevOptions) ProtoReflect() protoreflect.Message {
	mi := &file_bdev_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBdevOptions.ProtoReflect.Descriptor instead.
func (*ListBdevOptions) Descriptor() ([]byte, []int) {
	return file_bdev_proto_rawDescGZIP(), []int{0}
}

func (x *ListBdevOptions) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

type CreateBdevRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *CreateBdevRequest) Reset() {
	*x = CreateBdevRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bdev_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBdevRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBdevRequest) ProtoMessage() {}

func (x *CreateBdevRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bdev_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBdevRequest.ProtoReflect.Descriptor instead.
func (*CreateBdevRequest) Descriptor() ([]byte, []int) {
	return file_bdev_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBdevRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type CreateBdevResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bdev *Bdev `protobuf:"bytes,1,opt,name=bdev,proto3" json:"bdev,omitempty"`
}

func (x *CreateBdevResponse) Reset() {
	*x = CreateBdevResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bdev_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBdevResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBdevResponse) ProtoMessage() {}

func (x *CreateBdevResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bdev_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBdevResponse.ProtoReflect.Descriptor instead.
func (*CreateBdevResponse) Descriptor() ([]byte, []int) {
	return file_bdev_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBdevResponse) GetBdev() *Bdev {
	if x != nil {
		return x.Bdev
	}
	return nil
}

type DestroyBdevRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *DestroyBdevRequest) Reset() {
	*x = DestroyBdevRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bdev_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyBdevRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyBdevRequest) ProtoMessage() {}

func (x *DestroyBdevRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bdev_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyBdevRequest.ProtoReflect.Descriptor instead.
func (*DestroyBdevRequest) Descriptor() ([]byte, []int) {
	return file_bdev_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyBdevRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type Bdev struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the bdev
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the UUID which may or may not persist across restarts
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// the number of blocks
	NumBlocks uint64 `protobuf:"varint,3,opt,name=num_blocks,json=numBlocks,proto3" json:"num_blocks,omitempty"`
	// the size of each block
	BlkSize uint32 `protobuf:"varint,5,opt,name=blk_size,json=blkSize,proto3" json:"blk_size,omitempty"`
	// if the device is used by some other subsystem
	Claimed bool `protobuf:"varint,6,opt,name=claimed,proto3" json:"claimed,omitempty"`
	// the subsystem who uses the device
	ClaimedBy string `protobuf:"bytes,7,opt,name=claimed_by,json=claimedBy,proto3" json:"claimed_by,omitempty"`
	// any aliases the device uses
	Aliases string `protobuf:"bytes,8,opt,name=aliases,proto3" json:"aliases,omitempty"`
	// the URI the device was created from
	Uri string `protobuf:"bytes,9,opt,name=uri,proto3" json:"uri,omitempty"`
	// the product name of the device
	ProductName string `protobuf:"bytes,10,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	// the URI on which the device is exported
	ShareUri string `protobuf:"bytes,11,opt,name=share_uri,json=shareUri,proto3" json:"share_uri,omitempty"`
}

func (x *Bdev) Reset() {
	*x = Bdev{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bdev_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bdev) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bdev) ProtoMessage() {}

func (x *Bdev) ProtoReflect() protoreflect.Message {
	mi := &file_bdev_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bdev.ProtoReflect.Descriptor instead.
func (*Bdev) Descriptor() ([]byte, []int) {
	return file_bdev_proto_rawDescGZIP(), []int{4}
}

func (x *Bdev) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bdev) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Bdev) GetNumBlocks() uint64 {
	if x != nil {
		return x.NumBlocks
	}
	return 0
}

func (x *Bdev) GetBlkSize() uint32 {
	if x != nil {
		return x.BlkSize
	}
	return 0
}

func (x *Bdev) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *Bdev) GetClaimedBy() string {
	if x != nil {
		return x.ClaimedBy
	}
	return ""
}

func (x *Bdev) GetAliases() string {
	if x != nil {
		return x.Aliases
	}
	return ""
}

func (x *Bdev) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Bdev) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Bdev) GetShareUri() string {
	if x != nil {
		return x.ShareUri
	}
	return ""
}

type ListBdevResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bdevs []*Bdev `protobuf:"bytes,1,rep,name=bdevs,proto3" json:"bdevs,omitempty"`
}

func (x *ListBdevResponse) Reset() {
	*x = ListBdevResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bdev_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBdevResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBdevResponse) ProtoMessage() {}

func (x *ListBdevResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bdev_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBdevResponse.ProtoReflect.Descriptor instead.
func (*ListBdevResponse) Descriptor() ([]byte, []int) {
	return file_bdev_proto_rawDescGZIP(), []int{5}
}

func (x *ListBdevResponse) GetBdevs() []*Bdev {
	if x != nil {
		return x.Bdevs
	}
	return nil
}

type BdevShareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the bdev to share
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// the protocol to use
	Protocol     ShareProtocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=mayastor.v1.ShareProtocol" json:"protocol,omitempty"`
	AllowedHosts []string      `protobuf:"bytes,3,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"` // host (nqn's) which are allowed to connect to the target.
}

func (x *BdevShareRequest) Reset() {
	*x = BdevShareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bdev_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BdevShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BdevShareRequest) ProtoMessage() {}

func (x *BdevShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bdev_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BdevShareRequest.ProtoReflect.Descriptor instead.
func (*BdevShareRequest) Descriptor() ([]byte, []int) {
	return file_bdev_proto_rawDescGZIP(), []int{6}
}

func (x *BdevShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BdevShareRequest) GetProtocol() ShareProtocol {
	if x != nil {
		return x.Protocol
	}
	return ShareProtocol_NONE
}

func (x *BdevShareRequest) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

type BdevShareResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bdev *Bdev `protobuf:"bytes,1,opt,name=bdev,proto3" json:"bdev,omitempty"`
}

func (x *BdevShareResponse) Reset() {
	*x = BdevShareResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bdev_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BdevShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BdevShareResponse) ProtoMessage() {}

func (x *BdevShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bdev_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BdevShareResponse.ProtoReflect.Descriptor instead.
func (*BdevShareResponse) Descriptor() ([]byte, []int) {
	return file_bdev_proto_rawDescGZIP(), []int{7}
}

func (x *BdevShareResponse) GetBdev() *Bdev {
	if x != nil {
		return x.Bdev
	}
	return nil
}

type BdevUnshareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the bdev to unshare
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BdevUnshareRequest) Reset() {
	*x = BdevUnshareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bdev_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BdevUnshareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BdevUnshareRequest) ProtoMessage() {}

func (x *BdevUnshareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bdev_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BdevUnshareRequest.ProtoReflect.Descriptor instead.
func (*BdevUnshareRequest) Descriptor() ([]byte, []int) {
	return file_bdev_proto_rawDescGZIP(), []int{8}
}

func (x *BdevUnshareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_bdev_proto protoreflect.FileDescriptor

var file_bdev_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x64, 0x65, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x61,
	0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x64, 0x65, 0x76,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x64, 0x65, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69,
	0x22, 0x3b, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x64, 0x65, 0x76, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x64, 0x65, 0x76, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x64, 0x65, 0x76, 0x52, 0x04, 0x62, 0x64, 0x65, 0x76, 0x22, 0x26, 0x0a,
	0x12, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x42, 0x64, 0x65, 0x76, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x8d, 0x02, 0x0a, 0x04, 0x42, 0x64, 0x65, 0x76, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6b, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x6c, 0x6b, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c,
	0x61, 0x69, 0x6d, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x42, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x69,
	0x61, 0x73, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x55, 0x72, 0x69, 0x22, 0x3b, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x64, 0x65,
	0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x62, 0x64, 0x65,
	0x76, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x79, 0x61, 0x73,
	0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x64, 0x65, 0x76, 0x52, 0x05, 0x62, 0x64, 0x65,
	0x76, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x10, 0x42, 0x64, 0x65, 0x76, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x68,
	0x6f, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x48, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x3a, 0x0a, 0x11, 0x42, 0x64, 0x65, 0x76,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x62, 0x64, 0x65, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61,
	0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x64, 0x65, 0x76, 0x52, 0x04,
	0x62, 0x64, 0x65, 0x76, 0x22, 0x28, 0x0a, 0x12, 0x42, 0x64, 0x65, 0x76, 0x55, 0x6e, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xf3,
	0x02, 0x0a, 0x07, 0x42, 0x64, 0x65, 0x76, 0x52, 0x70, 0x63, 0x12, 0x4b, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x64, 0x65, 0x76, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x64, 0x65, 0x76, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x12, 0x1f, 0x2e, 0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x42, 0x64, 0x65, 0x76, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x64, 0x65, 0x76, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x1a, 0x1d, 0x2e, 0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x64, 0x65, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1d, 0x2e,
	0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x64, 0x65, 0x76,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d,
	0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x64, 0x65, 0x76, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44,
	0x0a, 0x07, 0x55, 0x6e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1f, 0x2e, 0x6d, 0x61, 0x79, 0x61,
	0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x64, 0x65, 0x76, 0x55, 0x6e, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x62, 0x73, 0x2f, 0x6d, 0x61, 0x79, 0x61, 0x73,
	0x74, 0x6f, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bdev_proto_rawDescOnce sync.Once
	file_bdev_proto_rawDescData = file_bdev_proto_rawDesc
)

func file_bdev_proto_rawDescGZIP() []byte {
	file_bdev_proto_rawDescOnce.Do(func() {
		file_bdev_proto_rawDescData = protoimpl.X.CompressGZIP(file_bdev_proto_rawDescData)
	})
	return file_bdev_proto_rawDescData
}

var file_bdev_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bdev_proto_goTypes = []interface{}{
	(*ListBdevOptions)(nil),        // 0: mayastor.v1.ListBdevOptions
	(*CreateBdevRequest)(nil),      // 1: mayastor.v1.CreateBdevRequest
	(*CreateBdevResponse)(nil),     // 2: mayastor.v1.CreateBdevResponse
	(*DestroyBdevRequest)(nil),     // 3: mayastor.v1.DestroyBdevRequest
	(*Bdev)(nil),                   // 4: mayastor.v1.Bdev
	(*ListBdevResponse)(nil),       // 5: mayastor.v1.ListBdevResponse
	(*BdevShareRequest)(nil),       // 6: mayastor.v1.BdevShareRequest
	(*BdevShareResponse)(nil),      // 7: mayastor.v1.BdevShareResponse
	(*BdevUnshareRequest)(nil),     // 8: mayastor.v1.BdevUnshareRequest
	(*wrapperspb.StringValue)(nil), // 9: google.protobuf.StringValue
	(ShareProtocol)(0),             // 10: mayastor.v1.ShareProtocol
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_bdev_proto_depIdxs = []int32{
	9,  // 0: mayastor.v1.ListBdevOptions.name:type_name -> google.protobuf.StringValue
	4,  // 1: mayastor.v1.CreateBdevResponse.bdev:type_name -> mayastor.v1.Bdev
	4,  // 2: mayastor.v1.ListBdevResponse.bdevs:type_name -> mayastor.v1.Bdev
	10, // 3: mayastor.v1.BdevShareRequest.protocol:type_name -> mayastor.v1.ShareProtocol
	4,  // 4: mayastor.v1.BdevShareResponse.bdev:type_name -> mayastor.v1.Bdev
	1,  // 5: mayastor.v1.BdevRpc.Create:input_type -> mayastor.v1.CreateBdevRequest
	3,  // 6: mayastor.v1.BdevRpc.Destroy:input_type -> mayastor.v1.DestroyBdevRequest
	0,  // 7: mayastor.v1.BdevRpc.List:input_type -> mayastor.v1.ListBdevOptions
	6,  // 8: mayastor.v1.BdevRpc.Share:input_type -> mayastor.v1.BdevShareRequest
	8,  // 9: mayastor.v1.BdevRpc.Unshare:input_type -> mayastor.v1.BdevUnshareRequest
	2,  // 10: mayastor.v1.BdevRpc.Create:output_type -> mayastor.v1.CreateBdevResponse
	11, // 11: mayastor.v1.BdevRpc.Destroy:output_type -> google.protobuf.Empty
	5,  // 12: mayastor.v1.BdevRpc.List:output_type -> mayastor.v1.ListBdevResponse
	7,  // 13: mayastor.v1.BdevRpc.Share:output_type -> mayastor.v1.BdevShareResponse
	11, // 14: mayastor.v1.BdevRpc.Unshare:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_bdev_proto_init() }
func file_bdev_proto_init() {
	if File_bdev_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bdev_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBdevOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bdev_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBdevRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bdev_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBdevResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bdev_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyBdevRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bdev_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bdev); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bdev_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBdevResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bdev_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BdevShareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bdev_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BdevShareResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bdev_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BdevUnshareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bdev_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bdev_proto_goTypes,
		DependencyIndexes: file_bdev_proto_depIdxs,
		MessageInfos:      file_bdev_proto_msgTypes,
	}.Build()
	File_bdev_proto = out.File
	file_bdev_proto_rawDesc = nil
	file_bdev_proto_goTypes = nil
	file_bdev_proto_depIdxs = nil
}
