// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Protocol over which the bdev/replica/nexus etc will be shared.
type ShareProtocol int32

const (
	ShareProtocol_NONE  ShareProtocol = 0 // not exposed
	ShareProtocol_NVMF  ShareProtocol = 1 // NVMe over Fabrics (TCP)
	ShareProtocol_ISCSI ShareProtocol = 2 // iSCSI
)

// Enum value maps for ShareProtocol.
var (
	ShareProtocol_name = map[int32]string{
		0: "NONE",
		1: "NVMF",
		2: "ISCSI",
	}
	ShareProtocol_value = map[string]int32{
		"NONE":  0,
		"NVMF":  1,
		"ISCSI": 2,
	}
)

func (x ShareProtocol) Enum() *ShareProtocol {
	p := new(ShareProtocol)
	*p = x
	return p
}

func (x ShareProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShareProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ShareProtocol) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ShareProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShareProtocol.Descriptor instead.
func (ShareProtocol) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Cipher to use for encryption.
type Cipher int32

const (
	Cipher_AES_CBC Cipher = 0
	Cipher_AES_XTS Cipher = 1
)

// Enum value maps for Cipher.
var (
	Cipher_name = map[int32]string{
		0: "AES_CBC",
		1: "AES_XTS",
	}
	Cipher_value = map[string]int32{
		"AES_CBC": 0,
		"AES_XTS": 1,
	}
)

func (x Cipher) Enum() *Cipher {
	p := new(Cipher)
	*p = x
	return p
}

func (x Cipher) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cipher) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (Cipher) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x Cipher) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cipher.Descriptor instead.
func (Cipher) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type MayastorFeatures struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// NVMe ANA enablement status.
	AsymmetricNamespaceAccess bool `protobuf:"varint,1,opt,name=asymmetricNamespaceAccess,proto3" json:"asymmetricNamespaceAccess,omitempty"`
	// LVM backend presence and enablement status.
	LogicalVolumeManager *bool `protobuf:"varint,2,opt,name=logicalVolumeManager,proto3,oneof" json:"logicalVolumeManager,omitempty"`
	// SnapshotRebuild presence and enablement status.
	SnapshotRebuild *bool `protobuf:"varint,3,opt,name=snapshotRebuild,proto3,oneof" json:"snapshotRebuild,omitempty"`
	// RDMA support for Mayastor nvmf target.
	RdmaCapableIoEngine *bool `protobuf:"varint,4,opt,name=rdmaCapableIoEngine,proto3,oneof" json:"rdmaCapableIoEngine,omitempty"`
	// Diskpool encryption capability.
	DiskpoolEncryption *bool `protobuf:"varint,5,opt,name=diskpoolEncryption,proto3,oneof" json:"diskpoolEncryption,omitempty"`
}

func (x *MayastorFeatures) Reset() {
	*x = MayastorFeatures{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MayastorFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MayastorFeatures) ProtoMessage() {}

func (x *MayastorFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MayastorFeatures.ProtoReflect.Descriptor instead.
func (*MayastorFeatures) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *MayastorFeatures) GetAsymmetricNamespaceAccess() bool {
	if x != nil {
		return x.AsymmetricNamespaceAccess
	}
	return false
}

func (x *MayastorFeatures) GetLogicalVolumeManager() bool {
	if x != nil && x.LogicalVolumeManager != nil {
		return *x.LogicalVolumeManager
	}
	return false
}

func (x *MayastorFeatures) GetSnapshotRebuild() bool {
	if x != nil && x.SnapshotRebuild != nil {
		return *x.SnapshotRebuild
	}
	return false
}

func (x *MayastorFeatures) GetRdmaCapableIoEngine() bool {
	if x != nil && x.RdmaCapableIoEngine != nil {
		return *x.RdmaCapableIoEngine
	}
	return false
}

func (x *MayastorFeatures) GetDiskpoolEncryption() bool {
	if x != nil && x.DiskpoolEncryption != nil {
		return *x.DiskpoolEncryption
	}
	return false
}

type MayastorBugFixes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Nexus rebuilds both the clusters allocated to the replica and its ancestors clusters
	NexusRebuildReplicaAncestry bool `protobuf:"varint,1,opt,name=nexusRebuildReplicaAncestry,proto3" json:"nexusRebuildReplicaAncestry,omitempty"`
}

func (x *MayastorBugFixes) Reset() {
	*x = MayastorBugFixes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MayastorBugFixes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MayastorBugFixes) ProtoMessage() {}

func (x *MayastorBugFixes) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MayastorBugFixes.ProtoReflect.Descriptor instead.
func (*MayastorBugFixes) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *MayastorBugFixes) GetNexusRebuildReplicaAncestry() bool {
	if x != nil {
		return x.NexusRebuildReplicaAncestry
	}
	return false
}

// Represents an encryption key that can be used to encrypt an
// entity like pool or lvol/replica.
type EncryptionKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the key.
	KeyName string `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	// The AES encryption key.
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// AES Key length.
	KeyLength uint32 `protobuf:"varint,3,opt,name=key_length,json=keyLength,proto3" json:"key_length,omitempty"`
	// key2 (required for AES_XTS).
	Key2 []byte `protobuf:"bytes,4,opt,name=key2,proto3,oneof" json:"key2,omitempty"`
	// The length of key2. Must be same as key_length.
	Key2Length *uint32 `protobuf:"varint,5,opt,name=key2_length,json=key2Length,proto3,oneof" json:"key2_length,omitempty"`
}

func (x *EncryptionKey) Reset() {
	*x = EncryptionKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptionKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionKey) ProtoMessage() {}

func (x *EncryptionKey) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionKey.ProtoReflect.Descriptor instead.
func (*EncryptionKey) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptionKey) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *EncryptionKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *EncryptionKey) GetKeyLength() uint32 {
	if x != nil {
		return x.KeyLength
	}
	return 0
}

func (x *EncryptionKey) GetKey2() []byte {
	if x != nil {
		return x.Key2
	}
	return nil
}

func (x *EncryptionKey) GetKey2Length() uint32 {
	if x != nil && x.Key2Length != nil {
		return *x.Key2Length
	}
	return 0
}

type EncryptionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Cipher to be used.
	Cipher Cipher `protobuf:"varint,1,opt,name=cipher,proto3,enum=mayastor.v1.Cipher" json:"cipher,omitempty"`
	// The encryption key.
	Key *EncryptionKey `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *EncryptionData) Reset() {
	*x = EncryptionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionData) ProtoMessage() {}

func (x *EncryptionData) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionData.ProtoReflect.Descriptor instead.
func (*EncryptionData) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptionData) GetCipher() Cipher {
	if x != nil {
		return x.Cipher
	}
	return Cipher_AES_CBC
}

func (x *EncryptionData) GetKey() *EncryptionKey {
	if x != nil {
		return x.Key
	}
	return nil
}

// This message represents name of the source for getting
// key parameter details.
type EncryptionSecret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *EncryptionSecret) Reset() {
	*x = EncryptionSecret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptionSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionSecret) ProtoMessage() {}

func (x *EncryptionSecret) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionSecret.ProtoReflect.Descriptor instead.
func (*EncryptionSecret) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *EncryptionSecret) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x80, 0x03, 0x0a, 0x10,
	0x4d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x12, 0x3c, 0x0a, 0x19, 0x61, 0x73, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x19, 0x61, 0x73, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x37,
	0x0a, 0x14, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x14,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x0f, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x52, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x01, 0x52, 0x0f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x12, 0x35, 0x0a, 0x13, 0x72, 0x64, 0x6d, 0x61, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6f, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x02, 0x52, 0x13, 0x72, 0x64, 0x6d, 0x61, 0x43, 0x61, 0x70, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x6f, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a,
	0x12, 0x64, 0x69, 0x73, 0x6b, 0x70, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52, 0x12, 0x64, 0x69, 0x73,
	0x6b, 0x70, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x42, 0x17, 0x0a, 0x15, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x42, 0x12, 0x0a, 0x10, 0x5f,
	0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x42,
	0x16, 0x0a, 0x14, 0x5f, 0x72, 0x64, 0x6d, 0x61, 0x43, 0x61, 0x70, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x6f, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x64, 0x69, 0x73, 0x6b,
	0x70, 0x6f, 0x6f, 0x6c, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x54,
	0x0a, 0x10, 0x4d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x42, 0x75, 0x67, 0x46, 0x69, 0x78,
	0x65, 0x73, 0x12, 0x40, 0x0a, 0x1b, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x52, 0x65, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x41, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1b, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x52, 0x65,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x41, 0x6e, 0x63, 0x65,
	0x73, 0x74, 0x72, 0x79, 0x22, 0xb3, 0x01, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x12, 0x17, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x32, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x6b,
	0x65, 0x79, 0x32, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x48, 0x01, 0x52, 0x0a, 0x6b, 0x65, 0x79, 0x32, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6b, 0x65, 0x79, 0x32, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6b,
	0x65, 0x79, 0x32, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x6b, 0x0a, 0x0e, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x06,
	0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d,
	0x61, 0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x52, 0x06, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x79, 0x61, 0x73, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b,
	0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2a, 0x0a, 0x10, 0x45, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x2a, 0x2e, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x4e, 0x56, 0x4d, 0x46, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x53, 0x43, 0x53,
	0x49, 0x10, 0x02, 0x2a, 0x22, 0x0a, 0x06, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x12, 0x0b, 0x0a,
	0x07, 0x41, 0x45, 0x53, 0x5f, 0x43, 0x42, 0x43, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x45,
	0x53, 0x5f, 0x58, 0x54, 0x53, 0x10, 0x01, 0x42, 0x45, 0x5a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x62, 0x73, 0x2f, 0x6d, 0x61,
	0x79, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x2d, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63,
	0x69, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x6f, 0x2d, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_goTypes = []interface{}{
	(ShareProtocol)(0),       // 0: mayastor.v1.ShareProtocol
	(Cipher)(0),              // 1: mayastor.v1.Cipher
	(*MayastorFeatures)(nil), // 2: mayastor.v1.MayastorFeatures
	(*MayastorBugFixes)(nil), // 3: mayastor.v1.MayastorBugFixes
	(*EncryptionKey)(nil),    // 4: mayastor.v1.EncryptionKey
	(*EncryptionData)(nil),   // 5: mayastor.v1.EncryptionData
	(*EncryptionSecret)(nil), // 6: mayastor.v1.EncryptionSecret
}
var file_common_proto_depIdxs = []int32{
	1, // 0: mayastor.v1.EncryptionData.cipher:type_name -> mayastor.v1.Cipher
	4, // 1: mayastor.v1.EncryptionData.key:type_name -> mayastor.v1.EncryptionKey
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MayastorFeatures); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MayastorBugFixes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptionKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptionSecret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_common_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
