// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: snapshot-rebuild.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SnapshotRebuildRpc_CreateSnapshotRebuild_FullMethodName  = "/mayastor.v1.SnapshotRebuildRpc/CreateSnapshotRebuild"
	SnapshotRebuildRpc_ListSnapshotRebuild_FullMethodName    = "/mayastor.v1.SnapshotRebuildRpc/ListSnapshotRebuild"
	SnapshotRebuildRpc_DestroySnapshotRebuild_FullMethodName = "/mayastor.v1.SnapshotRebuildRpc/DestroySnapshotRebuild"
)

// SnapshotRebuildRpcClient is the client API for SnapshotRebuildRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapshotRebuildRpcClient interface {
	// Create and start the rebuild job itself.
	CreateSnapshotRebuild(ctx context.Context, in *CreateSnapshotRebuildRequest, opts ...grpc.CallOption) (*SnapshotRebuild, error)
	// List all snapshot rebuild jobs.
	ListSnapshotRebuild(ctx context.Context, in *ListSnapshotRebuildRequest, opts ...grpc.CallOption) (*ListSnapshotRebuildResponse, error)
	// Destroys a snapshot rebuild job.
	DestroySnapshotRebuild(ctx context.Context, in *DestroySnapshotRebuildRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type snapshotRebuildRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotRebuildRpcClient(cc grpc.ClientConnInterface) SnapshotRebuildRpcClient {
	return &snapshotRebuildRpcClient{cc}
}

func (c *snapshotRebuildRpcClient) CreateSnapshotRebuild(ctx context.Context, in *CreateSnapshotRebuildRequest, opts ...grpc.CallOption) (*SnapshotRebuild, error) {
	out := new(SnapshotRebuild)
	err := c.cc.Invoke(ctx, SnapshotRebuildRpc_CreateSnapshotRebuild_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotRebuildRpcClient) ListSnapshotRebuild(ctx context.Context, in *ListSnapshotRebuildRequest, opts ...grpc.CallOption) (*ListSnapshotRebuildResponse, error) {
	out := new(ListSnapshotRebuildResponse)
	err := c.cc.Invoke(ctx, SnapshotRebuildRpc_ListSnapshotRebuild_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotRebuildRpcClient) DestroySnapshotRebuild(ctx context.Context, in *DestroySnapshotRebuildRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SnapshotRebuildRpc_DestroySnapshotRebuild_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotRebuildRpcServer is the server API for SnapshotRebuildRpc service.
// All implementations must embed UnimplementedSnapshotRebuildRpcServer
// for forward compatibility
type SnapshotRebuildRpcServer interface {
	// Create and start the rebuild job itself.
	CreateSnapshotRebuild(context.Context, *CreateSnapshotRebuildRequest) (*SnapshotRebuild, error)
	// List all snapshot rebuild jobs.
	ListSnapshotRebuild(context.Context, *ListSnapshotRebuildRequest) (*ListSnapshotRebuildResponse, error)
	// Destroys a snapshot rebuild job.
	DestroySnapshotRebuild(context.Context, *DestroySnapshotRebuildRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSnapshotRebuildRpcServer()
}

// UnimplementedSnapshotRebuildRpcServer must be embedded to have forward compatible implementations.
type UnimplementedSnapshotRebuildRpcServer struct {
}

func (UnimplementedSnapshotRebuildRpcServer) CreateSnapshotRebuild(context.Context, *CreateSnapshotRebuildRequest) (*SnapshotRebuild, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshotRebuild not implemented")
}
func (UnimplementedSnapshotRebuildRpcServer) ListSnapshotRebuild(context.Context, *ListSnapshotRebuildRequest) (*ListSnapshotRebuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshotRebuild not implemented")
}
func (UnimplementedSnapshotRebuildRpcServer) DestroySnapshotRebuild(context.Context, *DestroySnapshotRebuildRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroySnapshotRebuild not implemented")
}
func (UnimplementedSnapshotRebuildRpcServer) mustEmbedUnimplementedSnapshotRebuildRpcServer() {}

// UnsafeSnapshotRebuildRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotRebuildRpcServer will
// result in compilation errors.
type UnsafeSnapshotRebuildRpcServer interface {
	mustEmbedUnimplementedSnapshotRebuildRpcServer()
}

func RegisterSnapshotRebuildRpcServer(s grpc.ServiceRegistrar, srv SnapshotRebuildRpcServer) {
	s.RegisterService(&SnapshotRebuildRpc_ServiceDesc, srv)
}

func _SnapshotRebuildRpc_CreateSnapshotRebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRebuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotRebuildRpcServer).CreateSnapshotRebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotRebuildRpc_CreateSnapshotRebuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotRebuildRpcServer).CreateSnapshotRebuild(ctx, req.(*CreateSnapshotRebuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotRebuildRpc_ListSnapshotRebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotRebuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotRebuildRpcServer).ListSnapshotRebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotRebuildRpc_ListSnapshotRebuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotRebuildRpcServer).ListSnapshotRebuild(ctx, req.(*ListSnapshotRebuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotRebuildRpc_DestroySnapshotRebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySnapshotRebuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotRebuildRpcServer).DestroySnapshotRebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotRebuildRpc_DestroySnapshotRebuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotRebuildRpcServer).DestroySnapshotRebuild(ctx, req.(*DestroySnapshotRebuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotRebuildRpc_ServiceDesc is the grpc.ServiceDesc for SnapshotRebuildRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotRebuildRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mayastor.v1.SnapshotRebuildRpc",
	HandlerType: (*SnapshotRebuildRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSnapshotRebuild",
			Handler:    _SnapshotRebuildRpc_CreateSnapshotRebuild_Handler,
		},
		{
			MethodName: "ListSnapshotRebuild",
			Handler:    _SnapshotRebuildRpc_ListSnapshotRebuild_Handler,
		},
		{
			MethodName: "DestroySnapshotRebuild",
			Handler:    _SnapshotRebuildRpc_DestroySnapshotRebuild_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snapshot-rebuild.proto",
}
