apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor           
metadata:
  name: metrics-monitoring
  labels:
    app: metrics-servicemonitor   
spec:
  selector:                    
    matchLabels:               
      app: metrics-exporter-io-engine
  endpoints:                   
  - port: metrics