product:
    agentCoreContainerName: "agent-core"
    alertManagerPodPrefix: "alertmanager"
    controlPlaneAgent: "mayastor-agent-core"
    controlPlaneCoreAgent: "mayastor-agent-core"
    controlPlaneCsiController: "mayastor-csi-controller"
    controlPlaneEtcd: "mayastor-etcd"
    controlPlaneLoki: "mayastor-loki"
    controlPlaneMinio: "mayastor-minio"
    controlPlaneAlloy: "mayastor-alloy"
    controlPlanePoolOperator: "mayastor-operator-diskpool"
    controlPlaneRestServer: "mayastor-api-rest"
    controlPlaneLocalpvProvisioner: "mayastor-localpv-provisioner"
    controlPlaneObsCallhome: "mayastor-obs-callhome"
    cpuCount: "2"
    crdGroupName: "openebs.io"
    crdPoolsResourceName: "diskpools"
    csiDaemonsetName: "mayastor-csi-node"
    csiNodeServiceAppLabel: "csi-node"
    csiNodeServiceDaemonset: "mayastor-csi-node"
    csiNodeContainerName: "csi-node"
    csiProvisioner: "io.openebs.csi-mayastor"
    daemonsetName: "mayastor-io-engine"
    dataPlaneNats: "nats"
    dockerOrganisation: "openebs"
    engineLabel: "openebs.io/engine"
    engineLabelValue: "mayastor"
    etcdYaml: "etcd"
    eventBusNatsSts: "mayastor-nats"
    haNodeAgentDs: "mayastor-agent-ha-node"
    haNodeAgentPodPrefix: "mayastor-agent-ha-node"
    helmReleaseName: "mayastor"
    ioEnginePodLabelValue: "io-engine"
    ioEnginePodName: "mayastor-io-engine"
    jaegersCrdName: "jaegers.jaegertracing.io"
    kubectlPluginName: "kubectl-mayastor"
    kubectlPluginPort: 30011
    kubectlOpenebsPluginName: "kubectl-openebs"
    logConfigResources:
      - "mayastor-agent-core"
      - "mayastor-agent-ha-node"
      - "mayastor-alloy"
      - "mayastor-api-rest"
      - "mayastor-csi-controller"
      - "mayastor-csi-node"
      - "mayastor-etcd"
      - "mayastor-io-engine"
      - "mayastor-localpv-provisioner"
      - "mayastor-loki"
      - "mayastor-minio"
      - "mayastor-nats"
      - "mayastor-obs-callhome"
      - "mayastor-operator-diskpool"
    logDumpCsiAttacherName: "csi-attacher"
    logDumpCsiDriverRegistrarName: "csi-driver-registrar"
    logDumpCsiProvisionerName: "csi-provisioner"
    logDumpCsiResizerName: "csi-resizer"
    logDumpCsiSnapshotControllerName: "csi-snapshot-controller"
    logDumpCsiSnapshotterName: "csi-snapshotter"
    logDumpLokiMetricsName: "loki-metrics"
    LogDumpLokiReloaderName: "loki-reloader"
    logDumpDirs:
      - "agent-core"
      - "csi-controller"
      - "operator-diskpool"
      - "api-rest"
      - "agent-ha-node"
      - "csi-node"
      - "operator-diskpool"
      - "nats"
      - "etcd"
    logDumpEngineLabel: "io-engine"
    logDumpHaClusterName: "agent-ha-cluster"
    logDumpMetricsExporterLabel: "metrics-exporter"
    loggingLabel: "openebs.io/logging"
    logLevel: "debug"
    lokiStatefulset: "mayastor-loki"
    mayastorPluginName: "kubectl-mayastor"
    metricsPollingInterval: "30s"
    mongoAuthDatabase: "test"
    mongoAuthPassword: "admin123"
    mongoAuthRootPassword: "r00tAdmin"
    mongoAuthUsername: "admin"
    mongoDatabasePort: 27017
    mongoDefaultChartVersion: "16.5.0"
    mongoHelmRepo: "bitnami/mongodb"
    mongoHelmRepoName: "bitnami"
    mongoHelmRepoUrl: "https://charts.bitnami.com/bitnami"
    mongoReleaseName: "ms-mongo"
    natsPort: "4222"
    nvmeControllerModel: "Mayastor NVMe controller"
    partialRebuildCpTimeout: "240s"
    podLabelKey: "app"
    poolCrdName: "diskpools.openebs.io"
    postgresDatabaseName: "test"
    postgresAuthPassword: "admin123"
    postgresAuthRootPassword: "r00tAdmin"
    postgresAuthUsername: "admin"
    postgresDatabasePort: 5432
    postgresDefaultChartVersion: "15.5.18"
    postgresHelmRepo: "bitnami/postgresql"
    postgresHelmRepoName: "bitnami"
    postgresHelmRepoUrl: "https://charts.bitnami.com/bitnami"
    postgresReleaseName: "ms-app"
    postgresK8sLabelName: "app.kubernetes.io/name"
    postgresK8sLabelValue: "postgresql"
    productName: "mayastor"
    productNamespace: "mayastor"
    prometheusPodPrefix: "prometheus"
    prometheusPort: 30090
    promtailDaemonsetName: "mayastor-promtail"
    restApiPort: 8081
    restApiService: "mayastor-api-rest"
    statsConfigMapName: "mayastor-event-store"
    statsDeployment: "mayastor-obs-callhome"
    statsPort: "9090"
    statsService: "mayastor-obs-callhome-stats"
    upgradePodLabelValue: "upgrade"
    diskPoolAPIVersionMap:
      develop: "openebs.io/v1beta3"
      2.0.0: "openebs.io/v1alpha1"
      2.0.1: "openebs.io/v1alpha1"
      2.1.0: "openebs.io/v1alpha1"
      2.2.0: "openebs.io/v1alpha1"
      2.3.0: "openebs.io/v1alpha1"
      2.4.0: "openebs.io/v1beta1"
      2.5.0: "openebs.io/v1beta1"
      2.5.1: "openebs.io/v1beta1"
      2.6.1: "openebs.io/v1beta2"
      2.7.0: "openebs.io/v1beta2"
      2.7.1: "openebs.io/v1beta2"
      2.7.2: "openebs.io/v1beta2"
      2.7.3: "openebs.io/v1beta2"
      2.7.4: "openebs.io/v1beta2"
      2.7.5: "openebs.io/v1beta2"
      2.7.6: "openebs.io/v1beta2"
      2.8.0: "openebs.io/v1beta2"
      2.9.0: "openebs.io/v1beta3"
      2.9.1: "openebs.io/v1beta3"
      4.3.0: "openebs.io/v1beta3"
      4.3.1: "openebs.io/v1beta3"
      4.3.2: "openebs.io/v1beta3"
      4.3.3: "openebs.io/v1beta3"
      2.9.2: "openebs.io/v1beta3"
      2.9.3: "openebs.io/v1beta3"
      2.10.0: "openebs.io/v1beta3"
      4.4.0: "openebs.io/v1beta3"
    openebsToMayaVersionMap:
      4.3.0: "2.9.0"
      4.3.1: "2.9.1"
      4.3.2: "2.9.1"
      4.3.3: "2.9.2"
      4.4.0: "2.10.0"
    chartName: "mayastor"
    chartVersion: "0.0.0-main"
    localPVContainerName: "mayastor-localpv-provisioner"
    localEngineComponentPodLabelKey: "openebs.io/component-name"
    lvmEngineComponentDsPodLabelValue: "openebs-lvm-node"
    zfsEngineComponentDsPodLabelValue: "openebs-zfs-node"
    lvmEngineDaemonSetName: "openebs-lvm-localpv-node"
    zfsEngineDaemonSetName: "openebs-zfs-localpv-node"
    zfsEngineProvisioner: "zfs.csi.openebs.io"
    lvmEngineProvisioner: "local.csi.openebs.io"
    hostPathEngineProvisioner: "openebs.io/local"
    openEBSHelmReleaseName: "openebs"
    openEBSHelmRepoName: "openebs"
    openEBSHelmChartName: "openebs/openebs"
    openEBSHelmRepoUrl: "https://openebs.github.io/openebs"
    openEBSProductNamespace: "openebs"
    openEBSHelmChartVersion: "4.4.0-develop"
    lvmEngineControllerDeploymentName: "openebs-lvm-localpv-controller"
    lvmEngineLeaseName: "snapshot-controller-leader"
    lvmEnginePluginContainerName: "openebs-lvm-plugin"
    lvmEnginePluginDriverName: "local.csi.openebs.io"
    umbrellaOpenebsHelmChartName: "openebs"
    useUmbrellaOpenEBSChart: false
    disableEngines:
      - "lvm"
      - "zfs"
    zfsEnginePluginContainerName: "openebs-zfs-plugin"
    zfsEnginePluginDriverName: "zfs.csi.openebs.io"
    zfsEngineControllerDeploymentName: "openebs-zfs-localpv-controller"
    zfsEngineLeaseName: "external-resizer-zfs-csi-openebs-io"
    mayastorCsiControllerLogLevel: "trace"
    lokiIngesterChunkIdlePeriodTime: "30s"
    lokiIngesterChunkRetainPeriodTime: "15s"
    lokiIngesterMaxChunkAgeTime: "150s"
    ociRegistryUrl: "oci://ghcr.io/openebs/helm/openebs"
    ignoreLocalPvPodCheck: false
